### ISSUE TITLE
Splits editor sometimes does not close

### ISSUE THREAD

**Issue by jakoliath** [LiveSplit/LiveSplit#2229]
I do not know what consistently causes this issue, but two circumstances in which I have encountered this issue consistently:

-Trying to specify a layout file in the splits editor, then clicking OK or Cancel - the window will not close.
-Editing splits in a split file with a custom layout already set, immediately after opening the program, right-clicking, and selecting "Edit Splits". I try to change one segment time (which works fine), then click OK, and nothing happens; the window does not close, it does not freeze, it just simply doesn't respond to my clicks (this includes the X in the top corner).
--This sometimes happens when opening the Splits Editor, not making any changes, and trying to close it via X, or OK/Cancel.
---Note that this does not happen every time - it is inconsistent. Sometimes I can close the splits editor after making no changes, sometimes not - even from a fresh opening of the program.

**Comment by jakoliath** [comment]
Note: This issue has been resolved with a fresh install. Maybe an issue with the updating process?

**Comment by wooferzfg** [comment]
I'm not sure how to reproduce this, unfortunately.

**Comment by just-ero** [comment]
Does this issue persist on the most recent stable release of LiveSplit?

**Comment by jakoliath** [comment]
Yep!

I failed to mention before that I have only had this happen for split files where I have GIFs as split icons. Other splits with no icons do not have this problem.
