### ISSUE TITLE
Cannot join race channel after logging in with SRL details

### ISSUE THREAD

**Issue by JayWaaking** [LiveSplit/LiveSplit#990]
Start new race > log in details > https://gyazo.com/32ece5c5deadfb8211ba4c24376fdb12
stuck on joining channel. would this be an internet connection issue or something else?

**Comment by wooferzfg** [comment]
It might be caused by RaceBot not creating the race. It's hard to tell without seeing the IRC logs.

**Comment by JayWaaking** [comment]
It also happens when trying to join an existing race. Where can I find logs, or is that something I can't get easily?

**Comment by wooferzfg** [comment]
Oh, in that case, it's probably a different issue. Are you able to join races through a different IRC client?

**Comment by JayWaaking** [comment]
I'm able to join through other IRC clients, yes.

**Comment by JayWaaking** [comment]
Tried disabling my antivirus, but that still didn't work. Was there anything else I should try?

**Comment by chillex0** [comment]
I've been having this issue as well.

**Comment by JayWaaking** [comment]
Recently found out that mine was fixed
Did you mess with any registry stuff recently?

**Comment by chillex0** [comment]
I never touch registry. How did you get yours fixed?

**Comment by just-ero** [comment]
Does this issue persist in the most recent stable version of LiveSplit?

**Comment by JayWaaking** [comment]
I have no idea. This is from 6 years ago.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by wooferzfg** [comment]
Not planning to work on the SRL integration anymore.
